DB_FILE = "trading_bot.db"
INITIAL_BALANCE = 1000
INSTRUMENT_TYPE = "SPOT"
TIMEFRAME = "5m"

# Параметры стратегии скальпинга
SYMBOLS = [
    'BTC-USDT', 'ETH-USDT', 'XRP-USDT', 'BNB-USDT', 'SOL-USDT', 'DOGE-USDT', 'TRX-USDT',
    'ADA-USDT', 'LINK-USDT', 'XLM-USDT', 'SUI-USDT', 'BCH-USDT', 'HBAR-USDT',
    'AVAX-USDT', 'LTC-USDT', 'TON-USDT',
]  # Формат OKX
RSI_PERIOD = 14
RSI_BUY_THRESHOLD = 40
RSI_SELL_THRESHOLD = 60
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
POSITION_SIZE_PERCENT = 0.02
LEVERAGE_MIN = 25
LEVERAGE_MAX = 50
TAKE_PROFIT = 0.02
STOP_LOSS = 0.01
FEE_RATE = 0.0005
SLIPPAGE_PROBABILITY = 0.3
SLIPPAGE_RANGE = 0.0002
TICK_WINDOW = 100